apiVersion: v1
kind: pod 
metadata: 
  name: tainet-demo
  labels: 
    purpose: taint-demos

spec: 
  nodeselector: 
    topology.kubernetes.io/zone: us-east-1a
  containers: 
  - image: nginx
    name: nginx       