apiVersion: v1
kind: Pod 
metadata: 
  name: toleration2 
  labels: 
    purpose: "toleration-demo2"

spec: 
  containers: 
  - image: nginx 
    name: nginx 

  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoExecute"  

